#!/usr/bin/env python3
from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path
from typing import Any

import httpx

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "services/api/src"))

async def main() -> None:
    parser = argparse.ArgumentParser(description="Smoke test TaskR ↔ scrAIv linkage")
    parser.add_argument("--taskr-url", required=True, help="TaskR API base URL")
    parser.add_argument("--scr-url", required=True, help="scrAIv API base URL for verification")
    parser.add_argument("--tenant", required=True, help="Tenant identifier")
    parser.add_argument("--taskr-token", help="Bearer token for TaskR")
    parser.add_argument("--scr-token", help="Bearer token for scrAIv endpoint")
    args = parser.parse_args()

    task_payload = {
        "title": "Linkage Smoke",
        "description": "Generated by ping_scraiv_linkage.py",
        "list_id": None,
        "metadata_json": {"scr_link": {"session_id": "smoke", "client_id": "smoke"}},
    }

    headers = {"x-tenant-id": args.tenant, "Content-Type": "application/json"}
    if args.taskr_token:
        headers["authorization"] = f"Bearer {args.taskr_token}"

    async with httpx.AsyncClient(timeout=10.0) as client:
        # Fetch default list to attach task
        lists_resp = await client.get(f"{args.taskr_url.rstrip('/')}/lists", headers=headers)
        lists_resp.raise_for_status()
        lists = lists_resp.json()
        if not lists:
            raise SystemExit("No lists available for tenant; seed data first.")
        task_payload["list_id"] = lists[0]["list_id"]

        create_resp = await client.post(
            f"{args.taskr_url.rstrip('/')}/tasks",
            headers=headers,
            content=json.dumps(task_payload),
        )
        create_resp.raise_for_status()
        task = create_resp.json()
        task_id = task["task_id"]
        print(f"Created task {task_id}")

        # Allow forwarder to ship event
        await asyncio.sleep(2)

        scr_headers = {"x-tr-tenant": args.tenant}
        if args.scr_token:
            scr_headers["authorization"] = f"Bearer {args.scr_token}"
        linkage_resp = await client.get(
            f"{args.scr_url.rstrip('/')}/api/integrations/task-link/{task_id}",
            headers=scr_headers,
        )
        if linkage_resp.status_code == 200:
            print("scrAIv linkage found:")
            print(json.dumps(linkage_resp.json(), indent=2))
        else:
            print(f"scrAIv lookup returned {linkage_resp.status_code}: {linkage_resp.text}")


if __name__ == "__main__":
    asyncio.run(main())
